"""
Download and set up CodeQA data from HuggingFace.

Downloads the trajectory rollouts (train/val/test with embedded images)
and source data (original dataset, code images, metadata) needed to run
evaluations and training.

Usage:
    python setup_data.py                          # download everything to ./data
    python setup_data.py --data_dir /path/to/data # custom location
    python setup_data.py --trajectories-only      # skip source data
"""

import argparse
import os
import shutil

from huggingface_hub import hf_hub_download, snapshot_download


HF_REPO = "spatel-learn/codeqa-vagen-trajectories"


def download_trajectories(data_dir: str):
    """Download pre-computed trajectory rollouts (HF dataset splits)."""
    print("\n=== Downloading trajectory rollouts ===")
    traj_dir = os.path.join(data_dir, "trajectories")
    os.makedirs(traj_dir, exist_ok=True)

    # Download the HF dataset (Parquet files)
    snapshot_download(
        repo_id=HF_REPO,
        repo_type="dataset",
        local_dir=traj_dir,
        allow_patterns=["*.parquet", "*.arrow", "dataset_info.json", "state.json"],
    )
    print(f"  Downloaded to: {traj_dir}")
    return traj_dir


def download_source_data(data_dir: str):
    """Download source data files needed for running evaluations."""
    print("\n=== Downloading source data ===")

    source_dir = data_dir
    os.makedirs(source_dir, exist_ok=True)

    # Download source data files from the HF repo's 'source_data/' folder
    snapshot_download(
        repo_id=HF_REPO,
        repo_type="dataset",
        local_dir=source_dir,
        allow_patterns=[
            "source_data/**",
        ],
    )

    # Move files from source_data/ subfolder to expected locations
    src_subdir = os.path.join(source_dir, "source_data")
    if os.path.exists(src_subdir):
        for item in os.listdir(src_subdir):
            src = os.path.join(src_subdir, item)
            dst = os.path.join(source_dir, item)
            if not os.path.exists(dst):
                shutil.move(src, dst)
        # Clean up empty dir
        if os.path.exists(src_subdir) and not os.listdir(src_subdir):
            os.rmdir(src_subdir)

    print(f"  Source data in: {source_dir}")
    return source_dir


def generate_env_file(data_dir: str, script_dir: str):
    """Generate .env file with resolved paths."""
    env_path = os.path.join(script_dir, ".env")

    data_dir = os.path.abspath(data_dir)

    env_content = f"""# CodeQA-VAGEN Configuration (auto-generated by setup_data.py)

# ── Data paths ──
DATA_DIR={data_dir}
DATASET_PATH={data_dir}/prepared_dataset/all_repos_dataset.jsonl
IMAGES_DIR={data_dir}/code_images_8pt
CONTAMINATED_PATH={data_dir}/contaminated_questions_v3.json
NONTRUNCATED_PATH={data_dir}/nontruncated_repos.json

# ── Output paths ──
ROLLOUT_DIR={data_dir}/rollouts
LOG_DIR={script_dir}/logs

# ── Model settings ──
MODEL=Qwen/Qwen3-VL-8B-Instruct
HF_HOME=${{HOME}}/.cache/huggingface

# ── vLLM settings ──
VLLM_PORT=8000
TENSOR_PARALLEL_SIZE=4
MAX_MODEL_LEN=50000
MAX_IMAGES_PER_PROMPT=30

# ── Conda environment name ──
CONDA_ENV=vagen
"""
    with open(env_path, "w") as f:
        f.write(env_content)
    print(f"\n  Generated .env at: {env_path}")


def verify_data(data_dir: str):
    """Check that required files exist."""
    print("\n=== Verifying data ===")
    required = {
        "Dataset": "prepared_dataset/all_repos_dataset.jsonl",
        "Contaminated IDs": "contaminated_questions_v3.json",
        "Non-truncated info": "nontruncated_repos.json",
        "Code images dir": "code_images_8pt",
    }
    all_ok = True
    for name, rel_path in required.items():
        full_path = os.path.join(data_dir, rel_path)
        exists = os.path.exists(full_path)
        status = "OK" if exists else "MISSING"
        print(f"  [{status}] {name}: {full_path}")
        if not exists:
            all_ok = False

    return all_ok


def main():
    parser = argparse.ArgumentParser(description="Set up CodeQA data from HuggingFace")
    parser.add_argument(
        "--data_dir",
        default="./data",
        help="Directory to store data (default: ./data relative to this script)",
    )
    parser.add_argument(
        "--trajectories-only",
        action="store_true",
        help="Only download trajectory rollouts (skip source data)",
    )
    parser.add_argument(
        "--no-env",
        action="store_true",
        help="Skip generating .env file",
    )
    args = parser.parse_args()

    script_dir = os.path.dirname(os.path.abspath(__file__))

    # Resolve data_dir relative to script location if not absolute
    if not os.path.isabs(args.data_dir):
        data_dir = os.path.join(script_dir, args.data_dir)
    else:
        data_dir = args.data_dir

    os.makedirs(data_dir, exist_ok=True)
    print(f"Data directory: {data_dir}")

    # Download
    download_trajectories(data_dir)

    if not args.trajectories_only:
        download_source_data(data_dir)

        if verify_data(data_dir):
            print("\nAll source data files verified!")
        else:
            print("\nWARNING: Some source data files are missing.")
            print("You may need to manually place them in the data directory.")

    # Generate .env
    if not args.no_env:
        generate_env_file(data_dir, script_dir)

    print("\n=== Setup complete! ===")
    print(f"Data directory: {data_dir}")
    if not args.no_env:
        print(f"Config file: {os.path.join(script_dir, '.env')}")
    print("\nNext steps:")
    print("  1. Review and edit .env if needed")
    print("  2. Run evaluation: ./run.sh")
    print("  3. Or submit via SLURM: sbatch launch_slurm.sh")


if __name__ == "__main__":
    main()
